/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppAccountRouteImport } from './routes/_app/account'
import { Route as AppActivityRouteImport } from './routes/_app/activity'
import { Route as AppCleanupRouteImport } from './routes/_app/cleanup'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppActivityIndexRouteImport } from './routes/_app/activity/index'
import { Route as AppActivityRunningRouteImport } from './routes/_app/activity/running'
import { Route as AppCleanupIndexRouteImport } from './routes/_app/cleanup/index'
import { Route as AppCleanupArchiveRouteImport } from './routes/_app/cleanup/archive'
import { Route as AppCleanupTrashRouteImport } from './routes/_app/cleanup/trash'
import { Route as AppSettingsIndexRouteImport } from './routes/_app/settings/index'
import { Route as AppSettingsScanningRouteImport } from './routes/_app/settings/scanning'
import { Route as AppSettingsAuthenticationIndexRouteImport } from './routes/_app/settings/authentication/index'
import { Route as AppSettingsAuthenticationUsersRouteImport } from './routes/_app/settings/authentication/users'
import { Route as AppSettingsFleetIndexRouteImport } from './routes/_app/settings/fleet/index'
import { Route as AppSettingsFleetMachineIdRouteImport } from './routes/_app/settings/fleet/$machineId'
import { Route as AppSettingsFleetPairRouteImport } from './routes/_app/settings/fleet/pair'
import { Route as AppSettingsIntegrationsIndexRouteImport } from './routes/_app/settings/integrations/index'
import { Route as AppSettingsIntegrationsT3CodeRouteImport } from './routes/_app/settings/integrations/t3-code'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountRoute = AppAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppRoute,
} as any)
const AppActivityRoute = AppActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AppRoute,
} as any)
const AppCleanupRoute = AppCleanupRouteImport.update({
  id: '/cleanup',
  path: '/cleanup',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppActivityIndexRoute = AppActivityIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppActivityRoute,
} as any)
const AppActivityRunningRoute = AppActivityRunningRouteImport.update({
  id: '/running',
  path: '/running',
  getParentRoute: () => AppActivityRoute,
} as any)
const AppCleanupIndexRoute = AppCleanupIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppCleanupRoute,
} as any)
const AppCleanupArchiveRoute = AppCleanupArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => AppCleanupRoute,
} as any)
const AppCleanupTrashRoute = AppCleanupTrashRouteImport.update({
  id: '/trash',
  path: '/trash',
  getParentRoute: () => AppCleanupRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsScanningRoute = AppSettingsScanningRouteImport.update({
  id: '/scanning',
  path: '/scanning',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsAuthenticationIndexRoute =
  AppSettingsAuthenticationIndexRouteImport.update({
    id: '/authentication/',
    path: '/authentication/',
    getParentRoute: () => AppSettingsRoute,
  } as any)
const AppSettingsAuthenticationUsersRoute =
  AppSettingsAuthenticationUsersRouteImport.update({
    id: '/authentication/users',
    path: '/authentication/users',
    getParentRoute: () => AppSettingsRoute,
  } as any)
const AppSettingsFleetIndexRoute = AppSettingsFleetIndexRouteImport.update({
  id: '/fleet/',
  path: '/fleet/',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsFleetMachineIdRoute =
  AppSettingsFleetMachineIdRouteImport.update({
    id: '/fleet/$machineId',
    path: '/fleet/$machineId',
    getParentRoute: () => AppSettingsRoute,
  } as any)
const AppSettingsFleetPairRoute = AppSettingsFleetPairRouteImport.update({
  id: '/fleet/pair',
  path: '/fleet/pair',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsIntegrationsIndexRoute =
  AppSettingsIntegrationsIndexRouteImport.update({
    id: '/integrations/',
    path: '/integrations/',
    getParentRoute: () => AppSettingsRoute,
  } as any)
const AppSettingsIntegrationsT3CodeRoute =
  AppSettingsIntegrationsT3CodeRouteImport.update({
    id: '/integrations/t3-code',
    path: '/integrations/t3-code',
    getParentRoute: () => AppSettingsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/account': typeof AppAccountRoute
  '/activity': typeof AppActivityRouteWithChildren
  '/cleanup': typeof AppCleanupRouteWithChildren
  '/settings': typeof AppSettingsRouteWithChildren
  '/activity/running': typeof AppActivityRunningRoute
  '/cleanup/archive': typeof AppCleanupArchiveRoute
  '/cleanup/trash': typeof AppCleanupTrashRoute
  '/settings/scanning': typeof AppSettingsScanningRoute
  '/activity/': typeof AppActivityIndexRoute
  '/cleanup/': typeof AppCleanupIndexRoute
  '/settings/': typeof AppSettingsIndexRoute
  '/settings/authentication/users': typeof AppSettingsAuthenticationUsersRoute
  '/settings/fleet/$machineId': typeof AppSettingsFleetMachineIdRoute
  '/settings/fleet/pair': typeof AppSettingsFleetPairRoute
  '/settings/integrations/t3-code': typeof AppSettingsIntegrationsT3CodeRoute
  '/settings/authentication/': typeof AppSettingsAuthenticationIndexRoute
  '/settings/fleet/': typeof AppSettingsFleetIndexRoute
  '/settings/integrations/': typeof AppSettingsIntegrationsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/account': typeof AppAccountRoute
  '/': typeof AppIndexRoute
  '/activity/running': typeof AppActivityRunningRoute
  '/cleanup/archive': typeof AppCleanupArchiveRoute
  '/cleanup/trash': typeof AppCleanupTrashRoute
  '/settings/scanning': typeof AppSettingsScanningRoute
  '/activity': typeof AppActivityIndexRoute
  '/cleanup': typeof AppCleanupIndexRoute
  '/settings': typeof AppSettingsIndexRoute
  '/settings/authentication/users': typeof AppSettingsAuthenticationUsersRoute
  '/settings/fleet/$machineId': typeof AppSettingsFleetMachineIdRoute
  '/settings/fleet/pair': typeof AppSettingsFleetPairRoute
  '/settings/integrations/t3-code': typeof AppSettingsIntegrationsT3CodeRoute
  '/settings/authentication': typeof AppSettingsAuthenticationIndexRoute
  '/settings/fleet': typeof AppSettingsFleetIndexRoute
  '/settings/integrations': typeof AppSettingsIntegrationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/account': typeof AppAccountRoute
  '/_app/activity': typeof AppActivityRouteWithChildren
  '/_app/cleanup': typeof AppCleanupRouteWithChildren
  '/_app/settings': typeof AppSettingsRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_app/activity/running': typeof AppActivityRunningRoute
  '/_app/cleanup/archive': typeof AppCleanupArchiveRoute
  '/_app/cleanup/trash': typeof AppCleanupTrashRoute
  '/_app/settings/scanning': typeof AppSettingsScanningRoute
  '/_app/activity/': typeof AppActivityIndexRoute
  '/_app/cleanup/': typeof AppCleanupIndexRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/_app/settings/authentication/users': typeof AppSettingsAuthenticationUsersRoute
  '/_app/settings/fleet/$machineId': typeof AppSettingsFleetMachineIdRoute
  '/_app/settings/fleet/pair': typeof AppSettingsFleetPairRoute
  '/_app/settings/integrations/t3-code': typeof AppSettingsIntegrationsT3CodeRoute
  '/_app/settings/authentication/': typeof AppSettingsAuthenticationIndexRoute
  '/_app/settings/fleet/': typeof AppSettingsFleetIndexRoute
  '/_app/settings/integrations/': typeof AppSettingsIntegrationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/account'
    | '/activity'
    | '/cleanup'
    | '/settings'
    | '/activity/running'
    | '/cleanup/archive'
    | '/cleanup/trash'
    | '/settings/scanning'
    | '/activity/'
    | '/cleanup/'
    | '/settings/'
    | '/settings/authentication/users'
    | '/settings/fleet/$machineId'
    | '/settings/fleet/pair'
    | '/settings/integrations/t3-code'
    | '/settings/authentication/'
    | '/settings/fleet/'
    | '/settings/integrations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/account'
    | '/'
    | '/activity/running'
    | '/cleanup/archive'
    | '/cleanup/trash'
    | '/settings/scanning'
    | '/activity'
    | '/cleanup'
    | '/settings'
    | '/settings/authentication/users'
    | '/settings/fleet/$machineId'
    | '/settings/fleet/pair'
    | '/settings/integrations/t3-code'
    | '/settings/authentication'
    | '/settings/fleet'
    | '/settings/integrations'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/account'
    | '/_app/activity'
    | '/_app/cleanup'
    | '/_app/settings'
    | '/_app/'
    | '/_app/activity/running'
    | '/_app/cleanup/archive'
    | '/_app/cleanup/trash'
    | '/_app/settings/scanning'
    | '/_app/activity/'
    | '/_app/cleanup/'
    | '/_app/settings/'
    | '/_app/settings/authentication/users'
    | '/_app/settings/fleet/$machineId'
    | '/_app/settings/fleet/pair'
    | '/_app/settings/integrations/t3-code'
    | '/_app/settings/authentication/'
    | '/_app/settings/fleet/'
    | '/_app/settings/integrations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/account': {
      id: '/_app/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AppAccountRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/activity': {
      id: '/_app/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AppActivityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cleanup': {
      id: '/_app/cleanup'
      path: '/cleanup'
      fullPath: '/cleanup'
      preLoaderRoute: typeof AppCleanupRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/activity/': {
      id: '/_app/activity/'
      path: '/'
      fullPath: '/activity/'
      preLoaderRoute: typeof AppActivityIndexRouteImport
      parentRoute: typeof AppActivityRoute
    }
    '/_app/activity/running': {
      id: '/_app/activity/running'
      path: '/running'
      fullPath: '/activity/running'
      preLoaderRoute: typeof AppActivityRunningRouteImport
      parentRoute: typeof AppActivityRoute
    }
    '/_app/cleanup/': {
      id: '/_app/cleanup/'
      path: '/'
      fullPath: '/cleanup/'
      preLoaderRoute: typeof AppCleanupIndexRouteImport
      parentRoute: typeof AppCleanupRoute
    }
    '/_app/cleanup/archive': {
      id: '/_app/cleanup/archive'
      path: '/archive'
      fullPath: '/cleanup/archive'
      preLoaderRoute: typeof AppCleanupArchiveRouteImport
      parentRoute: typeof AppCleanupRoute
    }
    '/_app/cleanup/trash': {
      id: '/_app/cleanup/trash'
      path: '/trash'
      fullPath: '/cleanup/trash'
      preLoaderRoute: typeof AppCleanupTrashRouteImport
      parentRoute: typeof AppCleanupRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/scanning': {
      id: '/_app/settings/scanning'
      path: '/scanning'
      fullPath: '/settings/scanning'
      preLoaderRoute: typeof AppSettingsScanningRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/authentication/': {
      id: '/_app/settings/authentication/'
      path: '/authentication'
      fullPath: '/settings/authentication/'
      preLoaderRoute: typeof AppSettingsAuthenticationIndexRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/authentication/users': {
      id: '/_app/settings/authentication/users'
      path: '/authentication/users'
      fullPath: '/settings/authentication/users'
      preLoaderRoute: typeof AppSettingsAuthenticationUsersRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/fleet/': {
      id: '/_app/settings/fleet/'
      path: '/fleet'
      fullPath: '/settings/fleet/'
      preLoaderRoute: typeof AppSettingsFleetIndexRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/fleet/$machineId': {
      id: '/_app/settings/fleet/$machineId'
      path: '/fleet/$machineId'
      fullPath: '/settings/fleet/$machineId'
      preLoaderRoute: typeof AppSettingsFleetMachineIdRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/fleet/pair': {
      id: '/_app/settings/fleet/pair'
      path: '/fleet/pair'
      fullPath: '/settings/fleet/pair'
      preLoaderRoute: typeof AppSettingsFleetPairRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/integrations/': {
      id: '/_app/settings/integrations/'
      path: '/integrations'
      fullPath: '/settings/integrations/'
      preLoaderRoute: typeof AppSettingsIntegrationsIndexRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/integrations/t3-code': {
      id: '/_app/settings/integrations/t3-code'
      path: '/integrations/t3-code'
      fullPath: '/settings/integrations/t3-code'
      preLoaderRoute: typeof AppSettingsIntegrationsT3CodeRouteImport
      parentRoute: typeof AppSettingsRoute
    }
  }
}

interface AppActivityRouteChildren {
  AppActivityRunningRoute: typeof AppActivityRunningRoute
  AppActivityIndexRoute: typeof AppActivityIndexRoute
}

const AppActivityRouteChildren: AppActivityRouteChildren = {
  AppActivityRunningRoute: AppActivityRunningRoute,
  AppActivityIndexRoute: AppActivityIndexRoute,
}

const AppActivityRouteWithChildren = AppActivityRoute._addFileChildren(
  AppActivityRouteChildren,
)

interface AppCleanupRouteChildren {
  AppCleanupArchiveRoute: typeof AppCleanupArchiveRoute
  AppCleanupTrashRoute: typeof AppCleanupTrashRoute
  AppCleanupIndexRoute: typeof AppCleanupIndexRoute
}

const AppCleanupRouteChildren: AppCleanupRouteChildren = {
  AppCleanupArchiveRoute: AppCleanupArchiveRoute,
  AppCleanupTrashRoute: AppCleanupTrashRoute,
  AppCleanupIndexRoute: AppCleanupIndexRoute,
}

const AppCleanupRouteWithChildren = AppCleanupRoute._addFileChildren(
  AppCleanupRouteChildren,
)

interface AppSettingsRouteChildren {
  AppSettingsScanningRoute: typeof AppSettingsScanningRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
  AppSettingsAuthenticationUsersRoute: typeof AppSettingsAuthenticationUsersRoute
  AppSettingsFleetMachineIdRoute: typeof AppSettingsFleetMachineIdRoute
  AppSettingsFleetPairRoute: typeof AppSettingsFleetPairRoute
  AppSettingsIntegrationsT3CodeRoute: typeof AppSettingsIntegrationsT3CodeRoute
  AppSettingsAuthenticationIndexRoute: typeof AppSettingsAuthenticationIndexRoute
  AppSettingsFleetIndexRoute: typeof AppSettingsFleetIndexRoute
  AppSettingsIntegrationsIndexRoute: typeof AppSettingsIntegrationsIndexRoute
}

const AppSettingsRouteChildren: AppSettingsRouteChildren = {
  AppSettingsScanningRoute: AppSettingsScanningRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
  AppSettingsAuthenticationUsersRoute: AppSettingsAuthenticationUsersRoute,
  AppSettingsFleetMachineIdRoute: AppSettingsFleetMachineIdRoute,
  AppSettingsFleetPairRoute: AppSettingsFleetPairRoute,
  AppSettingsIntegrationsT3CodeRoute: AppSettingsIntegrationsT3CodeRoute,
  AppSettingsAuthenticationIndexRoute: AppSettingsAuthenticationIndexRoute,
  AppSettingsFleetIndexRoute: AppSettingsFleetIndexRoute,
  AppSettingsIntegrationsIndexRoute: AppSettingsIntegrationsIndexRoute,
}

const AppSettingsRouteWithChildren = AppSettingsRoute._addFileChildren(
  AppSettingsRouteChildren,
)

interface AppRouteChildren {
  AppAccountRoute: typeof AppAccountRoute
  AppActivityRoute: typeof AppActivityRouteWithChildren
  AppCleanupRoute: typeof AppCleanupRouteWithChildren
  AppSettingsRoute: typeof AppSettingsRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountRoute: AppAccountRoute,
  AppActivityRoute: AppActivityRouteWithChildren,
  AppCleanupRoute: AppCleanupRouteWithChildren,
  AppSettingsRoute: AppSettingsRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
